package pkg;

public class TestTrySplit {
   public void test() {
      Object obj = null;// 5

      try {
         obj = new Object();// 7
         return;// 17
      } catch (ArithmeticException var6) {// 8
         if (obj != null) {// 9
            System.out.println("a");// 10
         }

         throwMyException(var6.getMessage());// 13
      } finally {
         System.out.println("b");// 16
      }
   }// 14

   public static void throwMyException(String message) {
      throw new RuntimeException(message);// 21
   }
}

class 'pkg/TestTrySplit' {
   method 'test ()V' {
      0      4
      1      4
      9      7
      12      8
      15      9
      16      10
      17      10
      1a      11
      1b      11
      1c      11
      1d      11
      1e      11
      1f      11
      22      14
      23      14
      24      14
      25      14
      26      14
      31      18
      33      16
      34      16
      35      16
      36      16
      37      16
      38      16
   }

   method 'throwMyException (Ljava/lang/String;)V' {
      4      21
      8      21
   }
}

Lines mapping:
5 <-> 5
7 <-> 8
8 <-> 10
9 <-> 11
10 <-> 12
13 <-> 15
14 <-> 19
16 <-> 17
17 <-> 9
21 <-> 22
Not mapped:
18